# Generated by Django 3.2.8 on 2026-04-26 12:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0003_eggpredictorconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Counters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantNoticeSendLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('template_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='failed', max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=32)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('msg_id', models.CharField(blank=True, default='', max_length=64)),
                ('special_item_names', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'MerchantNoticeSendLog',
            },
        ),
        migrations.CreateModel(
            name='MerchantNoticeSubscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(max_length=128, unique=True)),
                ('openid_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('appid', models.CharField(blank=True, default='', max_length=64)),
                ('template_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('active', 'Active'), ('consumed', 'Consumed'), ('invalid', 'Invalid')], db_index=True, default='idle', max_length=16)),
                ('subscribed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('notify_count', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=32)),
                ('last_error_message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'MerchantNoticeSubscription',
            },
        ),
        migrations.CreateModel(
            name='MerchantSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slot_date', models.DateField(db_index=True)),
                ('round', models.PositiveSmallIntegerField(db_index=True)),
                ('total_rounds', models.PositiveSmallIntegerField(default=4)),
                ('next_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.CharField(blank=True, default='', max_length=32)),
                ('items_json', models.TextField(blank=True, default='[]')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('has_special_hit', models.BooleanField(db_index=True, default=False)),
                ('special_item_names', models.CharField(blank=True, default='', max_length=255)),
                ('notification_target_count', models.PositiveIntegerField(default=0)),
                ('notification_success_count', models.PositiveIntegerField(default=0)),
                ('notification_dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'MerchantSnapshot',
            },
        ),
        migrations.AddIndex(
            model_name='merchantsnapshot',
            index=models.Index(fields=['slot_date', 'round'], name='mch_slot_round_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantsnapshot',
            index=models.Index(fields=['has_special_hit', 'created_at'], name='mch_special_idx'),
        ),
        migrations.AddField(
            model_name='merchantnoticesubscription',
            name='last_notified_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notified_subscriptions', to='wxcloudrun.merchantsnapshot'),
        ),
        migrations.AddField(
            model_name='merchantnoticesendlog',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='wxcloudrun.merchantsnapshot'),
        ),
        migrations.AddField(
            model_name='merchantnoticesendlog',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='wxcloudrun.merchantnoticesubscription'),
        ),
        migrations.AddIndex(
            model_name='merchantnoticesubscription',
            index=models.Index(fields=['status', 'subscribed_at'], name='mnotice_active_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantnoticesubscription',
            index=models.Index(fields=['openid_hash', 'updated_at'], name='mnotice_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantnoticesendlog',
            index=models.Index(fields=['status', 'created_at'], name='mnotice_send_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='merchantnoticesendlog',
            constraint=models.UniqueConstraint(fields=('subscription', 'snapshot'), name='mnotice_send_subsnap_uq'),
        ),
    ]
