# Generated by Django 3.2.8 on 2026-04-26 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0004_auto_20260426_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantNoticeJobState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_key', models.CharField(max_length=64, unique=True)),
                ('guard_seconds', models.PositiveIntegerField(default=1800)),
                ('last_triggered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='idle', max_length=16)),
                ('last_result_json', models.TextField(blank=True, default='{}')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'MerchantNoticeJobState',
            },
        ),
        migrations.AddIndex(
            model_name='merchantnoticejobstate',
            index=models.Index(fields=['last_triggered_at', 'updated_at'], name='mnotice_job_run_idx'),
        ),
    ]
