# Generated by Django 3.2.8 on 2026-04-28 00:00

from django.db import migrations, models


def backfill_pending_count(apps, schema_editor):
    MerchantNoticeSubscription = apps.get_model('wxcloudrun', 'MerchantNoticeSubscription')
    MerchantNoticeSubscription.objects.filter(
        status='active',
        pending_count=0,
    ).update(pending_count=1)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0005_auto_20260426_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantnoticesubscription',
            name='pending_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_pending_count, noop_reverse),
    ]
