# Generated by Django 3.2.8 on 2026-04-28 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0006_merchantnoticesubscription_pending_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantnoticesubscription',
            name='selected_goods_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.CreateModel(
            name='MerchantNoticeDispatchJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_key', models.CharField(max_length=96, unique=True)),
                ('job_type', models.CharField(choices=[('snapshot', 'Snapshot'), ('manual', 'Manual')], db_index=True, default='snapshot', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial_failed', 'Partial Failed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=24)),
                ('payload_json', models.TextField(blank=True, default='{}')),
                ('target_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_jobs', to='wxcloudrun.merchantsnapshot')),
            ],
            options={
                'db_table': 'MerchantNoticeDispatchJob',
            },
        ),
        migrations.AddIndex(
            model_name='merchantnoticedispatchjob',
            index=models.Index(fields=['status', 'created_at'], name='mnotice_dispatch_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantnoticedispatchjob',
            index=models.Index(fields=['job_type', 'updated_at'], name='mnotice_dispatch_type_idx'),
        ),
    ]
