# Generated by Django 3.2 on 2026-04-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0007_dispatch_job_and_selected_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantnoticesubscription',
            name='daily_increment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merchantnoticesubscription',
            name='daily_increment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantnoticesubscription',
            name='daily_reward_unlock_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
